// Generated by CoffeeScript 1.10.0
(function() {
  var _, coloredRoutesLogger, colors, defaultTheme;

  colors = require('colors/safe');

  _ = require('lodash');

  defaultTheme = {
    verb: 'yellow',
    slash: 'blue',
    param: 'green',
    path: 'white'
  };

  coloredRoutesLogger = function(routes, colorSettings) {
    var action, coloredString, i, index, len, ref, results, route, routeSegment, routeSegments, verb;
    if (colorSettings == null) {
      colorSettings = {};
    }
    colors.setTheme(_.defaults(colorSettings, defaultTheme));
    results = [];
    for (route in routes) {
      action = routes[route];
      coloredString = "";
      ref = route.split(' '), verb = ref[0], route = ref[1];
      coloredString += " " + (colors.verb(verb)) + " ";
      routeSegments = route.split('/');
      for (index = i = 0, len = routeSegments.length; i < len; index = ++i) {
        routeSegment = routeSegments[index];
        if (index !== 0) {
          coloredString += "" + (colors.slash('/'));
        }
        if (routeSegment.charAt(0) === ':') {
          coloredString += "" + (colors.param(routeSegment));
        } else {
          coloredString += "" + (colors.path(routeSegment));
        }
      }
      results.push(console.log(coloredString));
    }
    return results;
  };

  module.exports = coloredRoutesLogger;

}).call(this);

//# sourceMappingURL=index.js.map
